spring:
  profiles:
    active:
      - prod
      - oauth-security
  application:
    name: algamoney-api
  main:
    allow-bean-definition-overriding: true
  flyway:
    baseline-on-migrate: true
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  messages:
    encoding: ISO-8859-1
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Pedro1714@#$
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

algamoney:
  allow-origin: https://localhost:8000
  security:
    enable-https: false

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {JDBC_DATABASE_URL}
    username: {JDBC_DATABASE_USERNAME}
    password: {JDBC_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

algamoney:
  allow-origin: https://algamoney-angular.herokuapp.com
  security:
    enable-https: true

