spring:
  application:
    name: algamoney-api
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
  flyway:
    baseline-on-migrate: true
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  messages:
    encoding: ISO-8859-1

algamoney:
  security:
    enable-https: false

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO