algamoney:
  allow-origin: https://algamoney-angular.herokuapp.com
  security:
    enable-https: true

spring:
  datasource:
    url: {JDBC_DATABASE_URL}
    username: {JDBC_DATABASE_USERNAME}
    password: {JDBC_DATABASE_PASSWORD}